// This file is auto generated by generateIndex.js

import { withStyle } from './withStyle';

import { ReactComponent as BmpIconSvg } from './svg/bmp-icon.svg';
import { ReactComponent as CssIconSvg } from './svg/css-icon.svg';
import { ReactComponent as FileIconSvg } from './svg/file-icon.svg';
import { ReactComponent as GifIconSvg } from './svg/gif-icon.svg';
import { ReactComponent as JpgIconSvg } from './svg/jpg-icon.svg';
import { ReactComponent as MdIconSvg } from './svg/md-icon.svg';
import { ReactComponent as PngIconSvg } from './svg/png-icon.svg';
import { ReactComponent as SvgIconSvg } from './svg/svg-icon.svg';

export const BmpIcon = withStyle(BmpIconSvg);
export const CssIcon = withStyle(CssIconSvg);
export const FileIcon = withStyle(FileIconSvg);
export const GifIcon = withStyle(GifIconSvg);
export const JpgIcon = withStyle(JpgIconSvg);
export const MdIcon = withStyle(MdIconSvg);
export const PngIcon = withStyle(PngIconSvg);
export const SvgIcon = withStyle(SvgIconSvg);
